# Generated by Django 5.1 on 2024-08-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=17)),
                ('symbol', models.CharField(max_length=10)),
                ('image_path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=19)),
                ('current_price', models.DecimalField(decimal_places=3, max_digits=18)),
                ('total_volume', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
