# Generated by Django 5.1 on 2024-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coindetails',
            name='current_price',
        ),
        migrations.AddField(
            model_name='coindetails',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=3, default=234, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
