# Generated by Django 5.1 on 2024-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0002_remove_coindetails_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindetails',
            name='current_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='coindetails',
            name='price_change_1h',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=6),
        ),
    ]
