# Generated by Django 5.1 on 2024-08-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0004_alter_coindetails_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindetails',
            name='price_change_1h',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
