# Generated by Django 5.1 on 2024-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0008_remove_coindetails_price_change_1h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindetails',
            name='price_change_1h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='coindetails',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
