# Generated by Django 5.1 on 2024-08-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0012_userwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
