# Generated by Django 5.1 on 2024-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0013_delete_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_coin', models.BooleanField(default=False)),
                ('coin_id', models.CharField(max_length=17)),
                ('symbol', models.CharField(max_length=10)),
                ('image_path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=19)),
            ],
        ),
    ]
