# Generated by Django 5.1 on 2024-08-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0016_userwallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWallet',
            new_name='MyWallet',
        ),
    ]
