# Generated by Django 5.1 on 2024-09-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0017_rename_userwallet_mywallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='coin_id',
        ),
    ]
