# Generated by Django 5.1 on 2024-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0018_remove_mywallet_coin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallet',
            name='coin_id',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
