# Generated by Django 5.1 on 2024-09-08 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0019_mywallet_coin_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallet',
            name='email',
            field=models.ForeignKey(default=121212, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='current_price',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='total_volume',
            field=models.IntegerField(max_length=12),
        ),
    ]
