# Generated by Django 5.1 on 2024-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0020_mywallet_email_alter_coindetails_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindetails',
            name='current_price',
            field=models.IntegerField(max_length=10),
        ),
    ]
