# Generated by Django 5.1 on 2024-09-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0021_alter_coindetails_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindetails',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='total_volume',
            field=models.IntegerField(),
        ),
    ]
