# Generated by Django 5.1 on 2024-09-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0022_alter_coindetails_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='email',
        ),
    ]
