# Generated by Django 5.1 on 2024-09-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0024_mywallet_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='email',
        ),
    ]
