# Generated by Django 5.1 on 2024-09-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0027_remove_coindetails_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindetails',
            name='current_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='coindetails',
            name='total_volume',
            field=models.IntegerField(default=1000),
        ),
    ]
