# Generated by Django 5.1 on 2024-09-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0029_remove_coindetails_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindetails',
            name='current_price',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=15),
        ),
        migrations.AddField(
            model_name='coindetails',
            name='total_volume',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=15),
        ),
    ]
