# Generated by Django 5.1 on 2024-09-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0030_coindetails_current_price_coindetails_total_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='email',
        ),
    ]
