# Generated by Django 5.1 on 2024-09-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0032_mywallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='user',
        ),
    ]
