# Generated by Django 5.1 on 2024-09-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0034_remove_mywallet_c_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallet',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
