# Generated by Django 5.1 on 2024-09-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_app', '0035_mywallet_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='has_coin',
        ),
    ]
